### PR TITLE
Cleanup code

### PR DESCRIPTION
**Pull request by Mesoptier**
* Added react and react-dom to devDependencies. As they are used during development.
* Updated ESLint and related packages.
* Updated `.eslintrc` and fixed code in `modules/`

### CODE REVIEW

**Comment by wagmiwiz** [comment]
Hey hey. Any chance of also doing the React 15.5 PropTypes cleaned up as part of this? It is the only offending module that still spits out the warning for me 😁 

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by ohall** [comment]
@Mesoptier @nikbora `prop-types` here https://github.com/sambernard/react-preload/pull/23

**Comment by RWOverdijk** [comment]
I've made a fork of this plugin. It works the same but has the PRs that cleanup and fix the PropTypes merged in. [You can find it here](https://www.npmjs.com/package/react-preloaded).

**Comment by sambernard** [comment]
A (belated) thanks for your contribution!

**Pull request merged**
