### PR TITLE
Use the prop-types package instead of deprecated PropTypes from React

### PR DESCRIPTION
**Pull request by ohall**
Use the prop-types package instead of deprecated PropTypes from main React Package.

screen shot 2017-05-24 at 3 36 23 pm

Thanks!

### CODE REVIEW

**Comment by wagmiwiz** [comment]
Hey @sambernard, any chance of merging this in and bumping up the version? Red consoles are so 2016.

**Comment by NeXTs** [comment]
@sambernard Hey Sam, please spend a minute to accept and publish this PR.

It's quite important for those of us who want to migrate to react v16

**Comment by malikid** [comment]
Hi guys, you can simply set npm package to
```
"react-preload": "git+https://github.com/malikid/react-preload.git"
```
before this PR is merged. It's forked from ohall:master and built.

**Comment by RWOverdijk** [comment]
I've made a fork of this plugin. It works the same but has the PRs that cleanup and fix the PropTypes merged in. [You can find it here](https://www.npmjs.com/package/react-preloaded).

**Comment by nuclearspike** [comment]
Is this package abandoned? There are completed PRs to fix issues that were completed months ago...

**Review by Krappt — APPROVED** [review]

**Comment by hiradyazdan** [comment]
is there any update on this?

**Comment by RWOverdijk** [comment]
https://www.npmjs.com/package/react-preloaded ^

**Comment by sambernard** [comment]
Hi! My apologies- I haven't been using this github account for the last 14 months so I missed the activity on this repo. I'll go ahead and go through these PRs/issues today.

**Pull request merged**
